# Generated by Django 4.2 on 2023-07-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetails',
            new_name='ContactDetail',
        ),
        migrations.RenameModel(
            old_name='EmailDetails',
            new_name='EmailDetail',
        ),
        migrations.RenameField(
            model_name='contactdetail',
            old_name='Messenger',
            new_name='Message',
        ),
    ]
