# Generated by Django 4.2 on 2023-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_contactdetails_contactdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='best_time_to_reach',
            new_name='hear_about',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='hear_about_us',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='reach_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='interests',
            field=models.TextField(),
        ),
    ]
