# Generated by Django 4.2 on 2023-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contactformentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='search_image/img')),
                ('place', models.CharField(max_length=200)),
                ('decoration', models.CharField(max_length=200)),
            ],
        ),
    ]
