# Generated by Django 4.2 on 2023-07-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_blogrecent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogrecent',
            old_name='title',
            new_name='titles',
        ),
    ]
