# Generated by Django 4.2 on 2023-07-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_tag_remove_blogpost_tags_blogpost_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='Tag',
        ),
    ]
