# Generated by Django 4.2 on 2023-07-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_name_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Tag',
            new_name='tags',
        ),
    ]
