# Generated by Django 4.2 on 2023-07-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_tags_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='nameS',
        ),
    ]
