# Generated by Django 4.2 on 2023-07-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_rename_name_tag_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nameS',
            new_name='name',
        ),
    ]
