# Generated by Django 4.2 on 2023-07-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_rename_names_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
